#ifndef DEV_DDM
#define DEV_DDM

#include <fftw3.h>

#include "stack.hpp"
#include "utils.hpp"

class DDM {
public:
    /**
     * Comment generated by GPT-3
     *
	 * Construct a DDM (Differential Dynamic Microscopy) object using a Stack and specified
	 * options.
     *
	 * This constructor initializes a DDM object based on the provided Stack, Delays, and
	 * options. It performs the following steps:
	 *   1. Initializes FFTW (Fastest Fourier Transform in the West) threads and sets the
	 *      number of threads.
	 *   2. Creates an FFTW plan for the given Stack, performing a real-to-complex discrete
	 *      Fourier transform (DFT).
	 *   3. Computes DDM differences using the FFT results, considering options such as log
	 *      scale and vectorization.
	 *   4. Shifts the DDM images to center the zero frequency, resulting in a square DDM
	 *      buffer.
     *
     * @param stack A reference to the Stack object containing input data.
	 * @param options Reference to the Options structure specifying parameters for DDM
	 *        computation.
     *
     * Details:
     *   - Uses FFTW for efficient Fourier transforms.
     *   - The DDM buffer dimensions depend on the options and input Stack dimensions.
	 *   - The DDM differences are computed based on options, considering log scale and
	 *     vectorization.
     *   - The final DDM buffer is shifted to center the zero frequency.
     */
    DDM(Stack &stack, utils::Options& options);
    ~DDM();

     /**
     * Comment generated by GPT-3
     *
     * Save the computed Differential Dynamic Microscopy (DDM) data to file.
     *
     * This function writes the DDM data to a file using the TinyTIFFWriter library.
     * It performs the following steps:
     *   1. Initializes a timer to measure the duration of the file-writing process.
     *   2. Opens a TinyTIFFWriter file with the specified output path, data type, dimensions, and format.
     *   3. Iterates through each frame of the DDM buffer and writes the data to the TinyTIFFWriter file.
     *   4. Closes the TinyTIFFWriter file after writing all frames.
     *
     */
    void save();

    const auto& get_ddm_buffer() const {
        return ddm_buffer;
    }
    const auto& get_lag_times() const {
        return lag_times;
    }

    const int raw_ddm_width, raw_ddm_height, raw_ddm_size;
    const int ddm_width, ddm_height, ddm_size;
    const int n_lags, max_lag_shift;

private:
    void compute_lags();
    /**
     * Comment generated by GPT-3
     *
     * Compute the Fast Fourier Transform (FFT) for the DDM object.
     *
	 * This function creates an FFTW plan, initializes FFTW threads, and computes the FFT
	 * for the given Stack. It performs the following steps:
     *   1. Initializes FFTW threads and sets the number of threads.
	 *   2. Creates an FFTW plan for the Stack, performing a real-to-complex discrete
	 *      Fourier transform (DFT).
	 *   3. Allocates memory for the complex FFT result based on Stack dimensions and
	 *      options.
     *   4. Executes the FFT plan to compute the FFT for the input Stack.
     *   5. Cleans up FFTW threads and destroys the FFT plan.
     */
    void compute_FFT();
     /**
     * Comment generated by GPT-3
     *
     * Compute the Differential Dynamic Microscopy (DDM) differences for the DDM object.
     *
	 * This function computes the DDM differences based on the FFT results and Delays
	 * information. It performs the following steps:
     *   1. Initializes variables for the width, height, and buffer size of the raw DDM.
     *   2. Allocates memory for the raw DDM buffer based on Delays information.
	 *   3. Computes DDM differences using optimized loops based on available vectorization
	 *      (AV512, AVX2 or autovectorization).
     */
    void compute_DDM();

    /**
     * Comment generated by GPT-3
     *
     * Perform the DDM (Differential Dynamic Microscopy) computation using AVX512
     * instructions.
     *
     * This function computes the DDM differences based on the FFT results, utilizing AVX512
     * instructions for vectorization. It performs the following steps:
     *   1. Initializes the raw DDM buffer to zeros.
     *   2. Utilizes AVX512 instructions for parallelized DDM computation.
     *   3. Computes squared differences and accumulates them in the raw DDM buffer.
     *   4. Normalizes the raw DDM buffer by the mean weight.
     */
    void ddm_loop_avx512();
    /**
    * Same as ddm_loop_avx512 with avx2 instruction sets
     */
    void ddm_loop_avx2();
    /**
     * Same as ddm_loop_avx512 with compiler autovecterization
     */
    void ddm_loop_autovec();
    /**
     * Comment generated by GPT-3
     *
     * Perform a shift operation on the raw DDM images.
     *
	 * After computing the DDM using appropriate methods (e.g., DDM::ddm_loop_avx), the "raw
	 * DDM images" exhibit symmetries due to the Fourier transform, resulting in "fft lobes"
	 * in the corners of the image. The width of the raw DDM is half the width of the real
	 * input signal plus 1, while the height remains the same.
     *
	 * The goal of this function is to transform the raw DDM into a square image with the
	 * zero frequency centered. To achieve this, the function operates on a buffer of odd
	 * width and height, referred to as ddm.
     *
	 * The shift operation involves copying and mirroring regions of the raw DDM to
	 * construct the final ddm buffer.
     *
     *                ┌───┐    ┌────────┐
     *                │ 1 │ -> │ 1'   2'│
     *                │ 4 │ -> │ 4'   3'│
     *                └───┘    └────────┘
     *                beg buf   final buf
     * Operations:
     *   - Copy Region 1 to Region 3'
     *   - Copy Region 4 to Region 2'
     *   - Mirror Region 3' to Region 1' and Region 2' to Region 4'
     *
     * Note : final dimension is odd.
     */
    void ddm_shift();

    utils::Options options;
    Stack& stack;

    std::vector<double> lag_times;
    std::vector<int> lag_shifts;

    fftwf_complex *stack_fft;
    float* raw_ddm_buffer;
    float* ddm_buffer;
};
#endif //DEV_DDM
